
services:
  - type: web
    name: momenta-deepfake-detector
    env: docker
    plan: free
    branch: main
    rootDir: implementation  # <--- THIS FIXES THE "NOT FOUND" ISSUE
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8501
    dockerCommand: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
